#!/bin/bash

# Stop and remove existing container
docker stop my-container || true
docker rm my-container || true

# Pull the latest Docker image
docker pull rahuldocker122/my-flask-app

# Run a new container with the Docker image
docker run -p 5000:5000 rahuldocker122/my-flask-app
