input:
  dataset_filename: InputDataSetLatest.csv
  read1k_filename: random1k.csv

model:
  nodes: 120
  optimizer: rmsprop
  loss: mse
  learning_rate: 0.001
  dropout_rate: 0.25
  activation: elu
  num_epochs: 100
  batch_size: 64
  validation_split: 0.1

logging:
  level: INFO
  filename: model_app.log
  format: "%(asctime)s - %(levelname)s - %(message)s"

files:
  model_filename: OptionValuationModel_opt
  scaler_filename: scalars_model_opt.save
connection_string: "DefaultEndpointsProtocol=https;AccountName=csg10032002ba1d46d6;AccountKey=T5TiTsmpHHAGl9FXpdmlHuVn4oNu2vJH/sILoTRewkVU2G27aNa/M1ZfYmpdzJZEJx0cEMHuN6Je+AStfcnEXw==;EndpointSuffix=core.windows.net"
container_name:  trainedmodel
