name: Docker Hub Deployment

on:
  push:
    branches:
      - main

env:
  DOCKER_HUB_USERNAME: rahuldocker122
  DOCKER_HUB_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    
    - name: Build Docker image
      run: docker build -t $DOCKER_HUB_USERNAME/my-flask-app .
    
    - name: Log in to Docker Hub
      run: docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
    
    - name: Push image to Docker Hub
      run: docker push $DOCKER_HUB_USERNAME/my-flask-app
      
    - name: SSH into Azure VM and deploy
      uses: appleboy/ssh-action@master
      with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ secrets.AZURE_VM_USERNAME }}
          password: ${{ secrets.AZURE_VM_PASSWORD }}
          source: ./deploy.sh
          target: /home/rahul/deploy.sh

    - name: Run deployment script
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AZURE_VM_IP }}
        username: ${{ secrets.AZURE_VM_USERNAME }}
        password: ${{ secrets.AZURE_VM_PASSWORD }}
        script: |
          chmod +x /home/rahul/deploy.sh
          /home/rahul/deploy.sh
